app/protected/controllers/ListingController.php
<?php

class ListingController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index', 'view', 'area', 'areaAjax', 'indexAjax'),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        
        // check if listing is not in solr, error 404
        if(!Listing::isSolrListing($id)) {
            throw new CHttpException(404,'Listing cannot be found.');
        }
        
        $countryName = Yii::app()->request->getQuery('country');
        $stateName = Yii::app()->request->getQuery('state');
        $cityName = Yii::app()->request->getQuery('city');
        $listingName = Yii::app()->request->getQuery('listingname');
        
        
        $listingUrlData = JoyUtilities::getListingUrl($id);
        $listingUrl = $listingUrlData['url'];
        $listingData = $listingUrlData['listingData'];
        
        if(!$countryName || !$stateName || !$cityName || !$listingName || $listingName != $listingData['listingName']) {
            $this->redirect($listingUrl);
        }
        
        Yii::app()->openexchanger->exchangeRates;        
        //Yii::app()->openexchanger->currency;
        
        // Calculate the popularity for View Details Page
        Listing::setPopularityScore($id, 'ViewDetail');
       
        
        $model = $this->loadModel($id);

        $userCompanyModel = UserCompany::model()->findByAttributes(array('userid'=>$model->foruserid), array('select'=>'name, id, logo')); 
        $companyName = $companyId = $companyLogo = '';
        if($userCompanyModel) {            
            $companyName = $userCompanyModel->name;
            $companyId = $userCompanyModel->id;
            $companyLogo = $userCompanyModel->logo;            
        }
        
        // For Meta Keywords
        $audienceTagArr = array();
        $audienceTags = ListingAudienceTag::getListingAudienceTag($id);        
        foreach($audienceTags as $audienceTag){
            $audienceTagArr[] = $audienceTag->audiencetag->name;            
        }
        
        // Set page meta keyword and page title
        $meta_keyword = str_replace(",", " ".$model->city->name.",", Yii::app()->params['meta_keyword']) ." ".$model->city->name;                
        Yii::app()->clientScript->registerMetaTag($meta_keyword .",". implode(",",$audienceTagArr) .",". $companyName, 'keywords', null, array('id'=>'meta_keywords'), 'meta_keywords');
        $this->pageTitle = $model->name." ".$model->mediatype->name ." ". $model->city->name ." ";
        
        // Page Breadcrumb
        $this->breadcrumbs=array(
            'Home' => JoyUtilities::getHomeUrl(),
            $model->country->name => Yii::app()->UrlManager->createUrl('listing/index', array('countryid' => $model->countryid) ),            
            $model->state->name => Yii::app()->UrlManager->createUrl('listing/index', array('countryid' => $model->countryid, 'stateid' => $model->stateid) ),
            $model->city->name." " => Yii::app()->UrlManager->createUrl('listing/index', array('countryid' => $model->countryid, 'stateid' => $model->stateid, 'cityid' => $model->cityid) ),
            $model->name,
        );

        $roleId = '';
        if(!Yii::app()->user->isGuest) {
            $roleId = Yii::app()->user->roleId;
        }
        //echo '<pre>';
        //print_r($model);
        
        $planData = Plan::getPlanWithListCount(Yii::app()->user->id);       
        $this->render('view', array(
            'model' => $model,
            'companyName' => $companyName,
            'companyId' => $companyId,
            'userId' => $model->foruserid,
            'roleId' => $roleId,
            'companyLogo' => $companyLogo,
            'planData' => $planData
        ));                
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        Yii::app()->openexchanger->exchangeRates;        
        if(Yii::app()->request->pathInfo == 's/mosaicview') {
            $listType = 'm';
        } else {
            // $listType = Yii::app()->request->getQuery('lt')? Yii::app()->request->getQuery('lt'): '';
            $listType = Yii::app()->request->getQuery('type')? Yii::app()->request->getQuery('type'): '';
        }
        //$metaKeyword = '';
        $pageTitle = '';
        $geoLatLng = Yii::app()->request->getQuery('geoloc');        
        $page = isset($_GET['page']) ? $_GET['page'] : 1;
        $upperLimit = Yii::app()->params['records_per_page'];
        $lowerLimit = ($page  - 1) * $upperLimit;
        
        if(isset($_REQUEST['ajax'])){
            $this->forward('indexAjax');
        }
        // used in index.php
        $dropDownFilter = array('1' => 'Most recent', '2' => 'Price', '3' => 'Popular');

        // default solrUrl
        $solrParams = array('sort' => 'datemodified desc', 'fq' => '');
        
        $breadcrumbArr = array(
            'Home' => JoyUtilities::getHomeUrl(),
        );
        
        // dropdown filter
        $filterId = Yii::app()->request->getQuery('filterid');
        if ($filterId == 2) {
            //$criteria['order'] = 'price DESC';
            $solrParams['sort'] = 'weeklyprice desc ';
        } else if ($filterId == 3) {
            //$criteria['order'] = 't.pscore DESC';
            $solrParams['sort'] = 'pscore desc';
        } else {
            //$criteria['order'] = 'datemodified DESC';
            $filterId = 1;
            $solrParams['sort'] = 'datemodified desc';
        }

        // filter price slider 
        $priceSlider = explode('-', Yii::app()->request->getQuery('priceslider'));
        if (count($priceSlider) > 1) {            
            // base on currency selected conv to usd to compare weeklyprice
            $newMinPrice = round(Yii::app()->openexchanger->convertCurrency($priceSlider[0], $this->ipCurrencyCode, 'USD'));
            $newMaxPrice = round(Yii::app()->openexchanger->convertCurrency($priceSlider[1], $this->ipCurrencyCode, 'USD'));
            //$criteria['condition']  .= ' AND weeklyprice between '.$priceSlider[0]. ' AND '. $priceSlider[1];
            $solrParams['fq'] .= (!empty($solrParams['fq'])) ? ' AND ' : '';
            $solrParams['fq'] .= 'weeklyprice:[' . $newMinPrice . ' TO ' . $newMaxPrice . ']';
        }
        
        // filter media type 
        $mediaTypeParam = Yii::app()->request->getQuery('mediatypeid');       
        $mediaTypeId = null;
        if (!empty($mediaTypeParam) && is_array($mediaTypeId = explode(",", $mediaTypeParam))) {
            $solrParams['fq'] .= (!empty($solrParams['fq'])) ? ' AND ' : '';
            $solrParams['fq'] .= '(';
            foreach($mediaTypeId as $mt) {
                $solrParams['fq'] .= ' mediatypeid:' . $mt . ' OR';
            }
            $solrParams['fq'] = rtrim($solrParams['fq'], 'OR');
            $solrParams['fq'] .= ')';
        }
        
        // distance        
        $proximity = is_numeric(Yii::app()->request->getQuery('proximity')) ? (int)Yii::app()->request->getQuery('proximity') : Yii::app()->params['proximity'];
        // lat lng with proximity
        $solrParams['fq'] .= " AND {!geofilt pt=$geoLatLng sfield=geoloc d=$proximity}";
        
        // solr query 
        $textSearch = Yii::app()->request->getQuery('textsearch');
        if (!empty($textSearch)) {
            $solrQuery = "name:*{$textSearch}* OR description:*{$textSearch}* OR mediatype:*{$textSearch}* OR audiencetag:*{$textSearch}*";
        } else {
            $solrQuery = '*:*';
        }
        // get listing from Solr
        if($listType =='p') {
            $result = Yii::app()->listingSearch->get($solrQuery, 0, 50000, $solrParams);
        } else {
            $result = Yii::app()->listingSearch->get($solrQuery, $lowerLimit, $upperLimit, $solrParams);
        }
        $listing = array();
        if (isset($result->response->numFound) && $result->response->numFound) {
            //echo "Results number is ".$result->response->numFound.'<br />';
            foreach ($result->response->docs as $doc) {
                $listing[] = $doc;
            }
        }
        
        $dataProvider = new ArrayDataProvider($listing, array(
                    'totalItemCount' => isset($result->response->numFound) ? $result->response->numFound : 0,
                    'pagination' => array(
                        'pageSize' => Yii::app()->params['records_per_page'],
                    ),
                ));

        // http://www.yiiframework.com/wiki/232/using-filters-with-cgridview-and-carraydataprovider/#c5501

        /* $dataProvider=new CActiveDataProvider('Listing', array(
          'criteria' => $criteria,
          'pagination' => array(
          'pageSize' => Yii::app()->params['records_per_page'],
          ),
          )); */
        
        // favorite star link
        $favLink = false;
        if (Yii::app()->user->isGuest) {
            $favLink = true;
        } else {
            $roleId = Yii::app()->user->roleId;
            if ($roleId == 2 || $roleId == 4) {
                $favLink = true;
            }
        }
        
        // Create Breadcrumb

app/protected/views/listing/_areaGrid.php
<div class="content_header">
    <h2>
        <!-- display Country/City -->
        <?php if ($countryName) {
            echo 'Listings In ' . $countryName . '';
        } else {
            echo 'Listings By Country';
        } ?>
    </h2>
</div>
<?php $_SESSION['listChar'] = 'abcd'; ?>
<div class="row col-sm-12 left country_listing"> 

    <!-- WHOLE VIEW IS RENDERED & CUSTOMIZED HERE -->
    <?php
    //if(is_numeric(isset($countryid))) { $link = '_country?countryid='.$countryid; } else { $link = '_country'; }
    $this->widget('zii.widgets.CListView', array(
        'id' => 'areaViewId',
        'dataProvider' => $dataProvider,
        'itemView' => '_country', // refers to the partial view named '_post'
        'viewData' => array(// own variables, for citi redirect
            'countryId' => isset($countryId) ? $countryId : 0
        ),
        'template' => "<div>
                            {items}
                        </div>",
        //'enablePagination'=> false,
        'afterAjaxUpdate' => "function(id, data) {
                                    abbrAll();
                                }",
    ));
    ?>
</div>
<?php if($updateBreadcrumb) { 
    $finalString = $this->widget('zii.widgets.CBreadcrumbs', array(
            'separator' => '<li class="separator"></li>',
            'tagName' => 'ul',
            'homeLink' => false,
            'links'=>$this->breadcrumbs,
            'inactiveLinkTemplate' => '<li>{label}</li>',
            'activeLinkTemplate' => '<li><a href="{url}">{label}</a></li>',
            'htmlOptions' => array('class' => 'breadcrumb left col-sm-9'),
        ),true);

    $finalString = preg_replace('/>\s<+/', '><', $finalString);
    ?>

<script type="text/javascript">
    updateBread();
    function updateBread() {
        
        //parentHTML = parentHTML.replace( new RegExp( "\>[\n\t ]+\<" , "g" ) , "><" ); 
        $('.navbar-collapse').html('<?php echo $finalString; ?>');
    }
</script>
<?php } ?>

app/protected/views/listing/_country.php
<?php
/* @var $this ListingController */
/* @var $data Listing */
?>


<?php 
    switch ($data->type) {

        case 'c':   if( $_SESSION['listChar'] != ucfirst($data->name[0]) ) {
                        echo "<div style='clear:both;'></div><h2>".ucfirst($data->name[0])."</h2>";
                        $_SESSION['listChar'] = ucfirst($data->name[0]);
                    }
                    echo "<div class='optionWidth'>".CHtml::ajaxLink(CHtml::encode($data->name), 
                            CHtml::normalizeUrl(array('/listing/areaAjax', 'countryid' => $data->id)),
                            array('update'=>'#updateView'),
                                    //'complete'=>'$.fn.yiiListView.update("areaViewId")'),
                            array('class'=>'c_'.ucfirst($data->name[0]))
                            )."</div>";
                    break;


        case 'ci':  if( $_SESSION['listChar'] != ucfirst($data->name[0]) ) {
                        echo "<div style='clear:both;'></div><h2>".ucfirst($data->name[0])."</h2>";
                        $_SESSION['listChar'] = ucfirst($data->name[0]);
                    }                    
                    echo "<div class='optionWidth'>".CHtml::link(CHtml::encode($data->name), 
                            array('/listing/index', 'countryid' => $countryId, 'stateid'=>$data->parentid, 'cityid' => $data->id), 
                            array('class'=>'c_'.ucfirst($data->name[0])))."</div>";
                    break;
    }

app/protected/views/listing/_form.php
<?php
/* @var $this ListingController */
/* @var $model Listing */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'listing-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'byuserid'); ?>
		<?php echo $form->textField($model,'byuserid'); ?>
		<?php echo $form->error($model,'byuserid'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'foruserid'); ?>
		<?php echo $form->textField($model,'foruserid'); ?>
		<?php echo $form->error($model,'foruserid'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'length'); ?>
		<?php echo $form->textField($model,'length',array('size'=>20,'maxlength'=>20)); ?>
		<?php echo $form->error($model,'length'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'width'); ?>
		<?php echo $form->textField($model,'width',array('size'=>20,'maxlength'=>20)); ?>
		<?php echo $form->error($model,'width'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'sizeunit'); ?>
		<?php echo $form->textField($model,'sizeunit'); ?>
		<?php echo $form->error($model,'sizeunit'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'basecurrency'); ?>
		<?php echo $form->textField($model,'basecurrency',array('size'=>20,'maxlength'=>20)); ?>
		<?php echo $form->error($model,'basecurrency'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'price'); ?>
		<?php echo $form->textField($model,'price',array('size'=>10,'maxlength'=>10)); ?>
		<?php echo $form->error($model,'price'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'priceduration'); ?>
		<?php echo $form->textField($model,'priceduration'); ?>
		<?php echo $form->error($model,'priceduration'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'otherdata'); ?>
		<?php echo $form->textField($model,'otherdata',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'otherdata'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'countryid'); ?>
		<?php echo $form->textField($model,'countryid'); ?>
		<?php echo $form->error($model,'countryid'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'stateid'); ?>
		<?php echo $form->textField($model,'stateid'); ?>
		<?php echo $form->error($model,'stateid'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'cityid'); ?>
		<?php echo $form->textField($model,'cityid'); ?>
		<?php echo $form->error($model,'cityid'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'street'); ?>
		<?php echo $form->textField($model,'street',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'street'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'geolat'); ?>
		<?php echo $form->textField($model,'geolat',array('size'=>9,'maxlength'=>9)); ?>
		<?php echo $form->error($model,'geolat'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'geolng'); ?>
		<?php echo $form->textField($model,'geolng',array('size'=>9,'maxlength'=>9)); ?>
		<?php echo $form->error($model,'geolng'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'zoomlevel'); ?>
		<?php echo $form->textField($model,'zoomlevel'); ?>
		<?php echo $form->error($model,'zoomlevel'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lighting'); ?>
		<?php echo $form->textField($model,'lighting'); ?>
		<?php echo $form->error($model,'lighting'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'mediatypeid'); ?>
		<?php echo $form->textField($model,'mediatypeid'); ?>
		<?php echo $form->error($model,'mediatypeid'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'description'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
		<?php echo $form->error($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'datecreated'); ?>
		<?php echo $form->textField($model,'datecreated'); ?>
		<?php echo $form->error($model,'datecreated'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'datemodified'); ?>
		<?php echo $form->textField($model,'datemodified'); ?>
		<?php echo $form->error($model,'datemodified'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

app/protected/views/listing/_mview.php
<?php
/* @var $this ListingController */
/* @var $data Listing */
// To calculate listing count
$currentListing = ($widget->dataProvider->getPagination()->pageSize * $widget->dataProvider->getPagination()->getCurrentPage()+1) + $index++;
?>

    <?php if($index==1) { ?>
        <input type="hidden" id="total_listing_count" value="<?php echo isset($totalCount) ? $totalCount : 0; ?>" />
        <input type="hidden" id="breadCrumbText" value='<?php echo isset($breadCrumbText) ? $breadCrumbText : ""; ?>' />
        <input type="hidden" id="pageTitleText" value="<?php echo isset($pageTitleText) ? htmlspecialchars($pageTitleText) : Yii::app()->name; ?>" />
        <input type="hidden" id="pageMetaKeywordText" value="<?php echo isset($pageMetaKeywordText) ? htmlspecialchars($pageMetaKeywordText) : ''; ?>" />        
    <?php } ?>

    <?php 
        if(!empty($data->filename)) {            
            $imagePath = JoyUtilities::getAwsFileUrl('small_'.$data->filename, 'listing');
            if(empty($imagePath)) {
                $imagePath = Yii::app()->baseUrl. '/images/site/img.png';
            }
        } else {
            $imagePath = Yii::app()->baseUrl. '/images/site/img.png';
        }  
    ?>
    
    <div class="left mosaicview" style="background: url(<?php echo $imagePath; ?>) no-repeat top left;">
        <?php if($favLink) { ?>
            <a href="javascript:void(0);" rel="activationPopup" class="add2fav" id="<?php echo $data->id; ?>"></a>
        <?php } ?>
        
        
        <h3><a href='<?php echo Yii::app()->urlManager->createUrl('listing/view', array('id'=>$data->id)); ?>'><?php echo $data->name; ?></a><br/>
            <span>  
                <?php echo CHtml::encode($data->mediatype); ?><br/>
                <?php echo CHtml::encode(JoyUtilities::formatNumber($data->length,2).' x '.JoyUtilities::formatNumber($data->width,2). ' ' . $data->sizeunit); ?><sup>2</sup>
            </span>
        </h3>

        <div class="foot-info">
            <h4><?php echo '<span class="dyn_ccode">' .CHtml::encode($this->ipCurrencyCode).'</span> <span class="dyn_price">'. CHtml::encode(JoyUtilities::formatNumber(Yii::app()->openexchanger->convertCurrency($data->price, $data->basecurrency, $this->ipCurrencyCode))).'</span> / '. $data->priceduration; ?><br/>
                <span><?php echo '<span class="base_ccode">'.CHtml::encode($data->basecurrency).'</span> <span class="base_price">'. CHtml::encode(JoyUtilities::formatNumber($data->price)).'</span> / '.$data->priceduration; ?></span></h4>
            <span class="btn btn-primary counter"><?php echo $currentListing; ?></span>
            <?php 
            $accurateGeolocation = $data->ea ? 1: 0 ;
            echo CHtml::hiddenField("getlatlng", '['.$data->lat.','.$data->lng.','.$accurateGeolocation.']', array('class'=>'listing_geoloc')); ?>
        </div>
    </div>

app/protected/views/listing/_view.php
<?php
/* @var $this ListingController */
/* @var $data Listing */
// To calculate listing count
$currentListing = ($widget->dataProvider->getPagination()->pageSize * $widget->dataProvider->getPagination()->getCurrentPage()+1) + $index++;
?>
<script>
    $('#body').removeAttr('id');
</script>
<!--<div class="view">-->    
    
    <?php if($index==1) { ?>
        <input type="hidden" id="total_listing_count" value="<?php echo isset($totalCount) ? $totalCount : 0; ?>" />
        <input type="hidden" id="breadCrumbText" value="<?php echo isset($breadCrumbText) ? htmlspecialchars($breadCrumbText) : ''; ?>" />
        <input type="hidden" id="pageTitleText" value="<?php echo isset($pageTitleText) ? htmlspecialchars($pageTitleText) : Yii::app()->name; ?>" />
        <input type="hidden" id="pageMetaKeywordText" value="<?php echo isset($pageMetaKeywordText) ? htmlspecialchars($pageMetaKeywordText) : ''; ?>" />
    <?php } ?>
        
    <?php if(!empty($data->filename)) {            
            $imagePath = JoyUtilities::getAwsFileUrl('tiny_'.$data->filename, 'listing');
            if(empty($imagePath)) {
                $imagePath = Yii::app()->baseUrl. '/images/site/img.png';
            }
        } else {
            $imagePath = Yii::app()->baseUrl. '/images/site/img.png';
        }     
    ?>
    <div class="left list-row">
        <div class="col-sm-7">
            <?php                                
                echo CHtml::image($imagePath, $data->name, array('title'=>$data->name)); ?>
            <h3><a href='<?php echo Yii::app()->urlManager->createUrl('listing/view', array('id'=>$data->id)); ?>'><?php echo $data->name; ?></a><br/>
                    <span><?php echo CHtml::encode($data->mediatype); ?><br/>
                    <?php echo CHtml::encode(JoyUtilities::formatNumber($data->length, 2).' x '.JoyUtilities::formatNumber($data->width, 2). ' ' . $data->sizeunit); ?><sup>2</sup></span>
                </h3>
        </div>
        <div class="col-sm-3">            
            <h4><?php echo '<span class="dyn_ccode">'.CHtml::encode($this->ipCurrencyCode).'</span> <span class="dyn_price">'.CHtml::encode(JoyUtilities::formatNumber(Yii::app()->openexchanger->convertCurrency($data->price, $data->basecurrency, $this->ipCurrencyCode))).'</span> / '. $data->priceduration; ?><br />
                <span><?php echo '<span class="base_ccode">'.CHtml::encode($data->basecurrency).'</span> <span class="base_price">'.CHtml::encode(JoyUtilities::formatNumber($data->price)).'</span> / '. $data->priceduration; ?></span>
            </h4>
            <?php 
                $accurateGeolocation = $data->ea ? 1: 0 ;
                echo CHtml::hiddenField("getlatlng", '['.$data->lat.','.$data->lng.','.$accurateGeolocation.']', array('class'=>'listing_geoloc')); ?>
        </div>

        <div class="col-sm-3 right">
            <?php if($favLink) { ?>
                <a href="javascript:void(0);" rel="activationPopup" class="add2fav" id="<?php echo $data->id; ?>"></a>
            <?php } ?>
            <span class="btn btn-primary counter"><?php echo $currentListing; ?></span>
        </div>
    </div>
    <div class="hr"></div>

app/protected/views/listing/admin.php
<?php
/* @var $this ListingController */
/* @var $model Listing */

$this->breadcrumbs=array(
	'Listings'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Listing', 'url'=>array('index')),
	array('label'=>'Create Listing', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#listing-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Listings</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'listing-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'byuserid',
		'foruserid',
		'name',
		'length',
		'width',
		/*
		'sizeunit',
		'basecurrency',
		'price',
		'priceduration',
		'otherdata',
		'countryid',
		'stateid',
		'cityid',
		'street',
		'geolat',
		'geolng',
		'zoomlevel',
		'lighting',
		'mediatypeid',
		'description',
		'status',
		'datecreated',
		'datemodified',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>